
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          uri: ''                                   #URL provided by zitadel
          client-id: ''                                                       #client id zitadel backend
          client-secret: ''     #secret zitadel backend
  datasource:
    url: jdbc:mariadb://localhost:3306/fineract_default
    username: root                                       #configuration of your database
    password: mysql
    driver-class-name: org.mariadb.jdbc.Driver
zitadel:
  url:
    front: 'http://localhost:4200'                       #url de frontend
  scope: "openid profile email urn:zitadel:iam:org:project:id:zitadel:aud"
  proyect:
    proyect_id: ""                                                      #resource id
    proyect_grand_id: ""                                                #grand id
  user-service:
    client_id: ""                                                                #name from  service user
    client_secret: ""     #secret from service user
  web-app:
    client_id: ""                                                       #frontend client id

logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug